"""Validation, storage and admin viewing of instructor credential documents."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath, PureWindowsPath
from typing import TYPE_CHECKING

from app.services.document_storage import DEFAULT_LINK_TTL_SECONDS, build_object_key

if TYPE_CHECKING:
    from datetime import datetime

    from fastapi import UploadFile

    from app.models import InstructorDocument
    from app.services.document_storage import DocumentStorage
    from app.services.identity_repository import IdentityRepository

ALLOWED_MIME_TYPES = {"application/pdf", "image/jpeg", "image/png"}
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024

MAGIC_BYTES = {
    "application/pdf": [b"%PDF"],
    "image/jpeg": [b"\xff\xd8\xff"],
    "image/png": [b"\x89PNG\r\n\x1a\n"],
}


class DocumentValidationError(ValueError):
    """Raised when a file's MIME type is not allowed or its content does not match it."""


class DocumentTooLargeError(ValueError):
    """Raised when an uploaded file exceeds the 10 MB limit."""


@dataclass
class UploadedInstructorDocuments:
    """Stored document record for an instructor (storage keys are not exposed)."""

    instructor_id: str
    document_id: str
    uploaded_at: datetime


@dataclass
class _ValidatedFile:
    content: bytes
    content_type: str
    original_filename: str | None


def _client_filename(upload: UploadFile) -> str | None:
    """Return the client's base filename (metadata only), stripped of any path."""
    if not upload.filename:
        return None
    name = PureWindowsPath(PurePosixPath(upload.filename).name).name
    return name[:255] or None


class InstructorDocumentService:
    """Validate instructor credential uploads, store them privately and list them for admins."""

    def __init__(self, *, repository: IdentityRepository, storage: DocumentStorage) -> None:
        """Store the identity repository and the document storage."""
        self._repository = repository
        self._storage = storage

    @staticmethod
    async def _read_and_validate(upload: UploadFile) -> _ValidatedFile:
        if upload.content_type not in ALLOWED_MIME_TYPES:
            msg = (
                f"Unsupported MIME type '{upload.content_type}'. Allowed: "
                f"{', '.join(sorted(ALLOWED_MIME_TYPES))}."
            )
            raise DocumentValidationError(msg)

        content = await upload.read()
        if len(content) > MAX_FILE_SIZE_BYTES:
            msg = "File exceeds 10MB limit."
            raise DocumentTooLargeError(msg)

        # D06: Validar Magic Bytes para evitar MIME spoofing
        mime = upload.content_type
        if mime in MAGIC_BYTES:
            signatures = MAGIC_BYTES[mime]
            matched = any(content.startswith(sig) for sig in signatures)
            if not matched:
                msg = (
                    "INVALID_FILE_CONTENT: File content does not match declared MIME type '"
                    f"{mime}'."
                )
                raise DocumentValidationError(msg)

        return _ValidatedFile(content, mime, _client_filename(upload))

    async def upload_documents(
        self, *, instructor_id: str, detran_credential: UploadFile, criminal_record: UploadFile
    ) -> UploadedInstructorDocuments:
        """Validate both files, store them privately and register the document record.

        Each file must be a PDF, JPEG or PNG of at most 10 MB whose magic bytes match the
        declared MIME type. Object keys are generated by the server (the client filename is
        kept only as storage metadata). Raises ``DocumentValidationError`` or
        ``DocumentTooLargeError`` on invalid files and ``UserNotFoundError`` if the
        instructor does not exist; stored objects are removed again on failure.
        """
        detran = await self._read_and_validate(detran_credential)
        criminal = await self._read_and_validate(criminal_record)

        detran_key = build_object_key(instructor_id, "detran-credential", detran.content_type)
        criminal_key = build_object_key(instructor_id, "criminal-record", criminal.content_type)
        # Check the instructor before uploading anything
        record = self._repository.add_instructor_document(
            instructor_id, detran_credential_url=detran_key, criminal_record_url=criminal_key
        )
        stored: list[str] = []
        try:
            for key, file in ((detran_key, detran), (criminal_key, criminal)):
                self._storage.put(
                    key,
                    file.content,
                    content_type=file.content_type,
                    original_filename=file.original_filename,
                )
                stored.append(key)
        except Exception:
            self._storage.delete(stored)
            raise

        return UploadedInstructorDocuments(
            instructor_id=instructor_id, document_id=record.id, uploaded_at=record.uploaded_at
        )

    def list_for_review(
        self, instructor_id: str, *, expires_in: int = DEFAULT_LINK_TTL_SECONDS
    ) -> list[dict[str, object]]:
        """Return the instructor's documents with short-lived links, for admin review."""
        return [
            self._serialize_for_review(document, expires_in)
            for document in self._repository.list_documents(instructor_id)
        ]

    def _serialize_for_review(
        self, document: InstructorDocument, expires_in: int
    ) -> dict[str, object]:
        def link(key: str | None) -> dict[str, str] | None:
            if not key:
                return None
            return {
                "url": self._storage.presigned_url(key, expires_in=expires_in),
                "content_type": _content_type_from_key(key),
            }

        return {
            "id": document.id,
            "uploaded_at": document.uploaded_at.isoformat().replace("+00:00", "Z"),
            "review_status": document.review_status,
            "detran_credential": link(document.detran_credential_url),
            "criminal_record": link(document.criminal_record_url),
            "expires_in": expires_in,
        }


_MIME_BY_EXTENSION = {"pdf": "application/pdf", "jpg": "image/jpeg", "png": "image/png"}


def _content_type_from_key(key: str) -> str:
    return _MIME_BY_EXTENSION.get(key.rsplit(".", 1)[-1], "application/octet-stream")
